# CLI tools
brew "node"
brew "uv"
brew "neonctl"
brew "gh"
brew "ripgrep"
brew "fzf"
brew "bat"
brew "eza"
brew "fd"
brew "jq"
brew "delta"
brew "lazygit"
brew "htop"
brew "pandoc"
cask "basictex"

# Apps
cask "iterm2"
cask "brave-browser"
cask "cursor"
cask "claude"
cask "slack"
cask "zoom"
cask "notion"
cask "microsoft-teams"
cask "fathom"
cask "granola"
cask "linearmouse"
cask "docker-desktop"
cask "ollama-app"
cask "raycast"
cask "tableplus"
cask "proxyman"

# Cursor extensions (VS Code compatible)
vscode "anthropic.claude-code"
vscode "ms-python.python"
vscode "charliermarsh.ruff"
vscode "eamodio.gitlens"
vscode "ms-toolsai.jupyter"
vscode "ms-python.debugpy"
# Note: remote-ssh and remote-containers must be installed manually in Cursor
# (Microsoft proprietary — not tracked correctly by brew bundle with Cursor)
vscode "ms-azuretools.vscode-docker"
vscode "usernamehw.errorlens"
vscode "redhat.vscode-yaml"
vscode "humao.rest-client"
